# Generated by Django 4.2.7 on 2026-03-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('company', models.CharField(max_length=300)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('salary', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(max_length=500)),
                ('source', models.CharField(max_length=50)),
                ('keyword', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(default=list)),
                ('match_score', models.IntegerField(default=0)),
                ('match_reason', models.TextField(blank=True)),
                ('matching_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('interviewing', 'Interviewing'), ('rejected', 'Rejected'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-match_score'],
            },
        ),
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='running', max_length=20)),
                ('jobs_scraped', models.IntegerField(default=0)),
                ('jobs_matched', models.IntegerField(default=0)),
                ('jobs_applied', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('log', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('skills', models.JSONField(default=list)),
                ('languages', models.JSONField(default=list)),
                ('frameworks', models.JSONField(default=list)),
                ('tools', models.JSONField(default=list)),
                ('experience', models.JSONField(default=list)),
                ('education', models.JSONField(default=list)),
                ('projects', models.JSONField(default=list)),
                ('summary', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
